### ISSUE TITLE
Problem downgrading firmware of Redmi Buds 3 Pro: Firmware info is incorrect.

### ISSUE THREAD

**Issue by gitnewcomer** [BurgerZ/MiBudsM8#20]
Hi, first, I want to thank you for this great tool!

I am trying to downgrade the firmware of my Redmi Buds 3 Pro from the chinese version 1.1.1.1 to global version 1.0.9.9 but I'm always getting this error "Can't update. Firmware info is incorrect."
If I try to flash again the modified chinese version 1.1.1.1, it starts flashing until 100% and then throws an error when it is trying to sync (maybe because the firmware installed is already the version 1.1.1.1).
What can it be, that makes the version 1.0.9.9 being rejected almost immediately and the modified chinese version 1.1.1.1 not?
All firmwares mentioned here are download from this repository...

**Comment by BurgerZ** [comment]
you can not just simple flash the firmware with the version lower than the installed one. You must modify the .bin file of the desired firmware to be able to install it over the newer version.
This is not an app bug, so closing this issue. I'll cover the topic of modifying firmware files in order to install/downgrade/interchange firmwares on earbuds soon. I'll post the tutorial here, and on my website.
